config/routes.rb
Rails.application.routes.draw do

  resources :favorites

  resources :attendees
  resources :atendees

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :events


  root :to => 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atendee.rb
class Atendee < ApplicationRecord
end

app/models/attendee.rb
class Attendee < ApplicationRecord

has_many :events
has_many :users, through: :events



end

app/models/event.rb
class Event < ApplicationRecord

	belongs_to :user

  has_many :favorites

  has_many :attendees


  mount_uploader :image, EventUploader
  mount_uploader :thumb_image, EventUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord


  has_many :users, through: :events
  has_many :events

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
		 :recoverable, :rememberable, :trackable, :validatable


	has_many :favorites

	has_many :events

	validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
end

app/controllers/atendees_controller.rb
class AtendeesController < ApplicationController
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_event_show, only: [:edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @users = User.all
    @favorited = Favorite.where(user_id: current_user)
    @events = Event.all
    @attending_events = Attendee.all
    @users = User.all
  end


  def show
    @event = Event.find(params[:id])
    @attendees = Attendee.where(event_id: @event)
    @users = User.all
    @location = "2912+Executive+Pkwy,Lehi,UT"
  end


  def new
    @event = Event.new
  end


  def edit
  end

  def create
    @event = current_user.events.create!(event_params)
    respond_to do |format|

      if @event.save
        format.html { redirect_to @event, notice: 'Your event was created'}
      else
        format.html {
          render :new
        }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Your event was updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Your event was deleted.' }
    end
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def set_event_show
      @event = current_user.events.find(params[:id])

      rescue ActiveRecord::RecordNotFound
      redirect_to(root_url, :notice => 'Record not found')
    end

    def event_params

      params.require(:event).permit(:title, :body, :user_id)

      params.require(:event).permit(:title, :body, :image, :thumb_image)

    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @events = Event.where(user_id: current_user.id)
    @rsvps = User.find(current_user.id).rsvps
    @favorites = User.find(current_user.id).favorites
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:destroy]

  def new
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.create!(user_id: current_user.id, event_id: params[:event_id])

    respond_to do |format|
      if @rsvp.save
        format.html { redirect_to root_url }
      end
    end
  end

  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end

  private

  def set_event
    @rsvp = Rsvp.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendees_helper.rb
module AtendeesHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/application.scss">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700|Gloria+Hallelujah|Patrick+Hand+SC|Walter+Turncoat" rel="stylesheet">
    <script>$('.carousel.carousel-slider').carousel({fullWidth: true});</script>

    <script>
      $(document).ready(function(){
      $('.slider').slider({
        indicators: true
      });
    });
    </script>
  </head>
  <body>


    <%= render 'shared/application_nav' %>

    



    <%= yield %>

    <%= js add_gritter(flash[:notice], title: "Events App Notification", sticky: false) %> 


  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<p>Welcome <%= current_user.name %></p>

<h4>My Events</h4>

  <% @events.each do |event| %>
    <p><%= event.title %></p>
    <p><%= event.body %></p>
    <p><%= event.location %></p>
    <hr>
  <% end %>

<h4>My RSVPs</h4>

  <% @rsvps.each do |rsvp| %>
    <p><%= rsvp.event.title %></p>
    <p><%= rsvp.event.location %></p>
    <hr>
  <% end %>

<h4>My Favorites</h4>

  <% @favorites.each do |favorite| %>
    <p><%= favorite.event.title %></p>
    <p><%= favorite.event.location %></p>
    <hr>
  <% end %>

app/views/shared/_application_nav.html.erb
<nav class="nav-masthead">

  <div>
    <%= link_to image_tag("nav.png"), "https://bottega.tech/", class: 'img navbar-brand' %>
  </div>
  <div class>
    <%= link_to "Home", root_path %>
    <%= link_to "Add a New Event", new_event_path if current_user %>  
  </div>
  <div class>
    <%= render "shared/devise_links" %>        
  </div>
	
</nav>

app/views/shared/_buttons.html.erb
<% if current_user %>


  <% if current_user.rsvps.where(event_id: event.id).count > 0 %>
  
    <%= link_to '<i class="fas fa-calendar-check"></i>'.html_safe, rsvp_path(@rsvps.where(event_id: event.id).first.id), method: :delete, class: "btn btn-success btn-custom" %>
  <% else %>
    
    <%= link_to '<i class="far fa-calendar-check"></i>'.html_safe, rsvps_path(:event_id => event.id), method: :post, class: "btn btn-secondary btn-custom" %>
  <% end %>

  <% if current_user.favorites.where(event_id: event.id).count > 0 %>
    
    <%= link_to '<i class="fas fa-star"></i>'.html_safe, favorite_path(@favorites.where(event_id: event.id).first.id), method: :delete, class: "btn btn-success btn-custom" %>
  <% else %>
    
    <%= link_to '<i class="far fa-star"></i>'.html_safe, favorites_path(:event_id => event.id), method: :post, class: "btn btn-secondary btn-custom" %>
  <% end %>

<% else %>
  <%= link_to '<i class="far fa-calendar-check"></i>'.html_safe, new_user_session_path, class: "btn btn-secondary btn-custom" %>
  <%= link_to '<i class="far fa-star"></i>'.html_safe, new_user_session_path, class: "btn btn-secondary btn-custom" %>
<% end %>

app/views/shared/_devise_links.html.erb
<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> 
  <%= link_to "Login", new_user_session_path %> 
<% end %>
</ul>